FROM nginx:1.18-alpine
USER root
RUN mkdir /etc/nginx/ssl
RUN apk upgrade --update-cache --available && \
    apk add openssl php7 php7-fpm php7-opcache supervisor&& \
    rm -rf /var/cache/apk/*
RUN openssl req -new -newkey rsa:2048 -days 365 -subj '/CN=mdm.ncsist.cn/O=myself/C=CN' -nodes -x509 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
COPY default.conf /etc/nginx/conf.d/default.conf
COPY supervisord.conf /etc/supervisord.conf
COPY ./webFiles /usr/share/nginx/html
RUN sed -i 's/;security.limit_extensions = .php .php3 .php4 .php5 .php7/security.limit_extensions = .php .plist/g' /etc/php7/php-fpm.d/www.conf
WORKDIR /
